name: Sticker Award

on:
  pull_request:
    types:
      - opened

jobs:
  award_sticker:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Author
        id: pr_author
        run: echo "::set-output name=author::${{ github.event.pull_request.user.login }}"

      - name: Award Sticker
        if: steps.pr_author.outputs.author != 'Neeraj1213'
        run: |
          # Replace 'your-username' with your GitHub username
          # Replace 'your-sticker-URL' with the URL of the sticker you want to use
          curl -X POST "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments" -H "Authorization: Bearer ${{ secrets.TOKEN_KEY}}" -d "{\"body\": \"Congratulations on your PR! Here's your sticker: [![Sticker](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIvI9pGp4Adko4of0biUmHWlgB85-e50HrWg1wcEsHF_doyv9WtxUtb-wYPayHcHuPwg0&usqp=CAU)](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIvI9pGp4Adko4of0biUmHWlgB85-e50HrWg1wcEsHF_doyv9WtxUtb-wYPayHcHuPwg0&usqp=CAU)\"}"


